// fetchRealGraph.js
//
// Pulls real road geometry from OpenStreetMap via the Overpass API for a
// given bounding box and converts it into the { nodes, edges } shape used
// by this project's backend (see src/data/sampleGraph.js for the shape).
//
// Run this on YOUR machine — it needs outbound internet access to
// overpass-api.de.
//
// Usage:
//   node scripts/fetchRealGraph.js > src/data/realGraph.js

const BBOX = [25.300, 82.960, 25.335, 82.985];

const OVERPASS_URL = "https://overpass-api.de/api/interpreter";

const query = `
[out:json][timeout:50];
way["highway"~"^(motorway|trunk|primary|secondary|tertiary|residential|unclassified)$"]
  (${BBOX[0]},${BBOX[1]},${BBOX[2]},${BBOX[3]});
(._;>;);
out body;
`;

async function main() {
  const res = await fetch(OVERPASS_URL, {
    method: "POST",
    body: new URLSearchParams({ data: query }),
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      "Accept": "application/json",
      "User-Agent": "RouteResilienceHackathon/1.0 (ISRO BAH 2026 prototype)"
    }
  });

  if (!res.ok) {
    const bodyText = await res.text();
    throw new Error(`Overpass request failed: ${res.status} ${res.statusText} — ${bodyText.slice(0, 200)}`);
  }

  const data = await res.json();

  const osmNodes = new Map();
  const ways = [];

  for (const el of data.elements) {
    if (el.type === "node") {
      osmNodes.set(el.id, { lat: el.lat, lng: el.lon });
    } else if (el.type === "way") {
      ways.push(el);
    }
  }

  const usedNodeIds = new Set();
  for (const way of ways) {
    for (const ref of way.nodes) usedNodeIds.add(ref);
  }

  const nodes = [...usedNodeIds].map((osmId) => {
    const n = osmNodes.get(osmId);
    return { id: `N${osmId}`, lat: n.lat, lng: n.lng, name: `Node ${osmId}` };
  });

  const edges = [];
  let edgeCounter = 1;
  for (const way of ways) {
    const wayId = `W${way.id}`;
    const roadName = way.tags?.name || `Unnamed road (${way.id})`;
    for (let i = 0; i < way.nodes.length - 1; i += 1) {
      const a = osmNodes.get(way.nodes[i]);
      const b = osmNodes.get(way.nodes[i + 1]);
      if (!a || !b) continue;
      const weight = haversineKm(a, b);
      edges.push({
        id: `E${edgeCounter++}`,
        wayId,
        roadName,
        source: `N${way.nodes[i]}`,
        target: `N${way.nodes[i + 1]}`,
        weight: Number(weight.toFixed(3)),
        occluded: false
      });
    }
  }

  const output = `// AUTO-GENERATED by fetchRealGraph.js from live OpenStreetMap data.
// Bounding box: [${BBOX.join(", ")}]
// Fetched: ${new Date().toISOString()}
// Re-run fetchRealGraph.js to refresh.

export const realGraph = {
  nodes: ${JSON.stringify(nodes, null, 2)},
  edges: ${JSON.stringify(edges, null, 2)}
};
`;

 const fs = await import("fs");
  fs.writeFileSync(new URL("../src/data/realGraph.js", import.meta.url), output, "utf8");
  console.error(`Fetched ${nodes.length} nodes and ${edges.length} edges from OSM. Saved to src/data/realGraph.js`);
}
function haversineKm(a, b) {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const lat1 = (a.lat * Math.PI) / 180;
  const lat2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

main().catch((err) => {
  console.error("Failed to fetch OSM data:", err.message);
  process.exit(1);
});